Map<String, String> symptomList = {
  "Itching": "itching",
  "Skin Rash": "skin_rash",
  "Nodal Skin Eruption": "nodal_skin_eruptions",
  "Continuous Sneezing": "continuous_sneezing",
  "Shivering": "shivering",
  "Muscle wasting": "muscle_wasting",
  "Vomiting": "vomiting",
  "Burning micturition": "burning_micturition",
  "Spotting urination": "spotting_urination",
  "Fatigue": "fatigue",
  "Weight gain": "weight_gain",
  "Anxiety": "anxiety",
  "Cold hands and feets": "cold_hand_and_feets",
  "Mood swings": "mood_swings",
  "Weight loss": "weight_loss",
  "Restlessness": "restlessness",
  "Lethargy": "lethargy",
  "Patches in throat": "patches_in_throat",
  "Irregular sugar level": "irregular_sugar_level",
  "Cough": "cough",
  "High fever": "high_fever",
  "Sunken eyes": "sunken_eyes",
  "Breathlessness": "breathlessness",
  "Sweating": "sweating",
  "Dehydration": "dehydration",
  "Indigestion": "indigestion",
  "Headache": "headache",
  "Yellowish skin": "yellowish_skin",
  "Dark urine": "dark_urine",
  "Nausea": "nausea",
  "Loss of appetite": "loss_of_appetite",
  "Pain behind eyes": "pain_behind_the_eyes",
  "Back pain": "back_pain",
  "Constipation": "constipation",
  "Abdominal Pain": "abdominal_pain",
  "Diarrhoea": "diarrhoea",
  "Mild Fever": "mild_fever",
  "Yellow urine": "yellow_urine",
  "Yellowing of eyes": "yellowing_of_eyes",
  "Acute liver failure": "acute_liver_failure",
  "Swelling of stomach": "swelling_of_stomach",
  "Swelled lymph nodes": "swelled_lymph_nodes",
  "Malaise": "malaise",
  "Blurred Vision": "blurred_and_distorted_vision",
  "Phlegm": "phlegm",
  "Throat irritation": "throat_irritation",
  "Redness of eyes": "redness_of_eyes",
  "Sinus pressure": "sinus_pressure",
  "Runny nose": "runny_nose",
  "Congestion": "congestion",
  "Chest Pain": "chest_pain",
  "Weakness in limbs": "weakness_in_limbs",
  "Fast heart rate": "fast_heart-rate",
  "Pain during bowel movements": "pain_during_bowel_movements",
  "Pain in anal": "pain_in_anal_region",
  "Blood stool": "blood_stool",
  "Irritation in anus": "irritation_in_anus",
  "Neck Pain": "neck_pain",
  "Dizziness": "dizziness",
  "Cramps": "cramps",
  "Bruising": "bruising",
  "Obesity": "obesity",
  "Swollen legs": "swollen_legs",
  "Swollen blood vessels": "swollen_blood_vessels",
  "Puffy face and eyes": "puffy_face_and_eyes",
  "Enlarged thyroid": "enlarged_thyroid",
  "Brittle nails": "brittle_nails",
  "Swollen extremeties": "swollen_extremeties",
  "Extra material contacts": "extra_material_contacts",
  "Excessive Hunger": "excessive_hunger",
  "Drying and tingling lips": "drying_and_tingling_lips",
  "Slurred speech": "slurred_speech",
  "Knee pain": "knee_pain",
  "Muscle weakness": "muslce_weakness",
  "Hip joint pain": "hip_joint_pain",
  "Stiff neck": "stiff_neck",
  "Swelling joints": "swelling_joints",
  "Movement stiffness": "movement_stiffness",
  "Spinning movements": "spinning_movements",
  "Loss of balance": "loss_of_balance",
  "Unsteadiness": "unsteadiness",
  "Weakness of one body side": "weakness_of_one_body_side",
  "Loss of smell": "loss_of_smell",
  "Bladder discomfort": "bladder_discomfort",
  "Foul smell of urine": "foul_smell_of_urine",
  "Continuous feel of urine": "continuous_feel_of_urine",
  "Passage of gases": "passage_of_gases",
  "Internal Itching": "internal_itching",
  "Toxic lookSymptom(typhosis": "toxic_lookSymptom(typhosis",
  "Depression": "depression",
  "Irritability": "irritability",
  "Muscle Pain": "muscle_pain",
  "Altered sensorium": "altered_sensorium",
  "Red spor over body": "red_spot_over_body",
  "Belly pain": "belly_pain",
  "Abnormal menstruation": "abnormal_menstruation",
  "Dischromic patches": "dischromic _patches",
  "Watering from eyes": "watering_from_eyes",
  "Increased appetite": "increased_appetite",
  "Polyuria": "polyuria",
  "Family history": "family_history",
  "Mucoid Sputum": "mucoid_sputum",
  "Rusty_sputum": "rusty_sputum",
  "Lack of concentration": "lack_of_concentration",
  "Visual disturbance": "visual disturbance",
  "Receiving blood transfusion": "receiving_blood_transfusion",
  "Receiving unsterile injection": "receiving_unsterile_injections",
  "Coma": "Coma",
  "Stomach bleeding": "stomach_bleeding",
  "Distention of abdomen": "distention_of_abdomen",
  "Alcohol consumption": "history_of_alcohol_consumption",
  "Fluid overload": "fluid_overload",
  "Blood in sputum": "blood_in_sputum",
  "Prominent veins on calf": "prominent_veins_on_calf",
  "Palpitation": "palpitation",
  "Painful walking": "painful_walking",
  "Pus filled pimples": "pus_filled_pimples",
  "Blackheads": "blackheads",
  "Scurring": "scurring",
  "Skin peeling": "skin_peeling",
  "Silver like dusting": "silver_like_dusting",
  "Small dents in nails": "small_dents_in_nails",
  "Inflammatory nails": "inflammatory_nails",
  "Blister": "blister",
  "Red sore around nose": "red_sore_around_nose",
  "Yellow Crust": "yellow_crust_ooze",
};
